---
- name: Update package cache (Fedora)
  ansible.builtin.dnf:
    update_cache: true
  become: true
  when: package_update | default(true)

- name: Upgrade packages (Fedora)
  ansible.builtin.dnf:
    name: "*" # package-latest warning
    state: latest
  become: true
  when: package_upgrade | default(false)

- name: Install common packages for Fedora
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: present
  loop: "{{ dev_packages.Fedora.values() | list }}"
  when: item is not none and item != 'null'
  become: true
