---
- name: Install development tools (Arch) # No packages left after removing overlap
  ansible.builtin.pacman: # community.general.pacman if not builtin
    name: []
    state: present
  become: true
