---
- name: Install development tools (Arch)
  pacman:
    name:
      - git
      - vim
      - zsh
      - base-devel
      - ripgrep
      - fd
      - bat
      - eza
      - fzf
    state: present
  become: yes
