---
- name: Install development tools (Fedora)
  dnf:
    name:
      - git
      - vim
      - zsh
      - "@Development Tools"
      - ripgrep
      - fd-find
      - bat
      - eza
      - fzf
    state: present
  become: yes
