---
- name: Install font packages (Fedora)
  ansible.builtin.dnf:
    name: "{{ item.value.Fedora }}"
    state: present
  loop: "{{ font_packages | dict2items }}"
  when: item.value.Fedora is defined and item.value.Fedora is not none
  become: true

- name: Update font cache
  ansible.builtin.command: fc-cache -fv
  become: true
  changed_when: false
  check_mode: false
