---
- name: Install font packages (Ubuntu)
  ansible.builtin.apt:
    name: "{{ item.value.Ubuntu }}"
    state: present
  loop: "{{ font_packages | dict2items }}"
  when: item.value.Ubuntu is defined and item.value.Ubuntu is not none
  become: true

- name: Create local fonts directory
  ansible.builtin.file:
    path: "{{ xdg_data_home }}/fonts"
    state: directory
    mode: '0755'

- name: Update font cache
  ansible.builtin.command: fc-cache -fv
  become: false # Fonts installed to user's XDG directory
  changed_when: false
  check_mode: false
